services:
  - type: web
    name: inkpad-compiler
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://inkpad.shadowbox.games,https://inkpad.netlify.app
      - key: PORT
        value: 10000
      - key: MAX_COMPILE_TIME
        value: 30000
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100