// client/src/ink-monarch.ts
import type { languages } from "monaco-editor";

export const inkLanguageId = "ink";

export const languageDefinition: languages.IMonarchLanguage = {
  defaultToken: "",
  tokenPostfix: ".ink",

  keywords: [
    "VAR", "CONST", "LIST", "INCLUDE", "EXTERNAL", "function",
    "return", "temp", "else", "END", "DONE", "true", "false",
  ],
  builtInFunctions: [
    "CHOICE_COUNT", "TURNS", "TURNS_SINCE", "READ_COUNT",
    "RANDOM", "SEED_RANDOM",
    "LIST_COUNT", "LIST_MIN", "LIST_MAX", "LIST_ALL", "LIST_INVERT",
    "LIST_VALUE", "LIST_RANGE", "LIST_RANDOM",
    "MIN", "MAX", "POW", "FLOOR", "CEILING", "INT", "FLOAT",
  ],
  operators: [
    "=", "==", "!=", "<", ">", "<=", ">=", "!", "&&", "||",
    "+", "-", "*", "/", "%", "++", "--",
    "+=", "-=", "*=", "/=", "%=", "&=",
    "?", "!?", "^", "and", "or", "not", "mod", "has", "hasnt",
  ],
  escapes: /\\(?:[abfnrtv\\"'#{}\[\]]|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,
  symbols: /[=><!~?:&|^+\-*\/%]+/,
  identifier: /[A-Za-z_\u00c0-\u024f\u0370-\u03ff\u0400-\u06ff\u4e00-\u9fff\uac00-\ud7af][A-Za-z0-9_\u00c0-\u024f\u0370-\u03ff\u0400-\u06ff\u4e00-\u9fff\uac00-\ud7af]*/,

  tokenizer: {
    root: [
      { include: "@comments" },

      [/^(\s*)(INCLUDE)(\s+)(\S+)/, ["white", "keyword.include", "white", "string.filename"]],
      [/^(\s*)(EXTERNAL)(\s+)(@identifier)/, ["white", "keyword.declaration", "white", { token: "entity.name.function", next: "@headerTail" }]],
      [/^(\s*)(VAR)(\s+)(@identifier)/, ["white", "keyword.declaration", "white", { token: "variable.global", next: "@expressionLine" }]],
      [/^(\s*)(CONST)(\s+)(@identifier)/, ["white", "keyword.declaration", "white", { token: "variable.constant", next: "@expressionLine" }]],
      [/^(\s*)(LIST)(\s+)(@identifier)/, ["white", "keyword.declaration", "white", { token: "variable.list", next: "@expressionLine" }]],

      [/^(\s*)(={2,})(\s*)(function\b)(\s*)(@identifier)/, ["white", "delimiter.knot", "white", "keyword.function", "white", { token: "entity.name.function", next: "@headerTail" }]],
      [/^(\s*)(={2,})(\s*)(@identifier)/, ["white", "delimiter.knot", "white", { token: "entity.name.knot", next: "@headerTail" }]],
      [/^(\s*)(=)(\s*)(@identifier)/, ["white", "delimiter.knot", "white", { token: "entity.name.stitch", next: "@headerTail" }]],
      [/^(\s*)(={2,})(?=\s*(?:\/\/|\/\*|$))/, ["white", "delimiter.knot"]],

      [/^(\s*)((?:\*\s*)+)/, ["white", { token: "delimiter.choice", next: "@weaveLine" }]],
      [/^(\s*)((?:\+\s*)+)/, ["white", { token: "delimiter.choice.sticky", next: "@weaveLine" }]],
      [/^(\s*)((?:-\s*)+)(?!>)/, ["white", { token: "delimiter.gather", next: "@weaveLine" }]],

      [/^(\s*)(TODO)\b/, ["white", { token: "keyword.todo", next: "@narrativeLine" }]],
      [/^(\s*)(~)/, ["white", { token: "keyword.tilde", next: "@expressionLine" }]],

      [/\\#/, "string.escape"],
      [/#/, "delimiter.tag", "@tag"],
      { include: "@diverts" },
      [/<>/, "keyword.glue"],

      [/(\{)(\s*)(stopping|cycle|once|shuffle(?:\s+(?:once|stopping))?)(\s*)(:)/, ["delimiter.curly", "white", "keyword.multiline", "white", { token: "delimiter.colon", next: "@curlyContent" }]],
      [/(\{)(\s*)([&~!$])(?=[^}\r\n]*\|)/, ["delimiter.curly", "white", { token: "keyword.alternative.type", next: "@sequence" }]],
      [/\{(?=[^}\r\n]*\|)/, "delimiter.curly", "@sequence"],
      [/\{(?=\s*$)/, "delimiter.curly", "@curlyContent"],
      [/\{/, "delimiter.curly", "@curlyExpression"],
      [/\}/, "delimiter.curly"],

      [/[ \t\r\n]+/, "white"],
    ],

    comments: [
      [/\/\*/, "comment", "@blockComment"],
      [/\/\/.*$/, "comment"],
    ],

    blockComment: [
      [/[^\/*]+/, "comment"],
      [/\*\//, "comment", "@pop"],
      [/[\/*]/, "comment"],
    ],

    tag: [
      [/^./, { token: "@rematch", next: "@pop" }],
      { include: "@comments" },
      [/#/, "delimiter.tag"],
      [/[^#\r\n]+/, "entity.name.tag"],
      [/$/, "", "@pop"],
    ],

    headerTail: [
      [/^./, { token: "@rematch", next: "@pop" }],
      { include: "@comments" },
      [/\(/, "delimiter.parenthesis", "@parameters"],
      [/={1,}/, "delimiter.knot"],
      [/[ \t]+/, "white"],
      [/$/, "", "@pop"],
    ],

    parameters: [
      { include: "@comments" },
      [/\bref\b/, "keyword.parameter"],
      { include: "@diverts" },
      [/@identifier/, "variable.parameter"],
      [/,/, "delimiter.comma"],
      [/\)/, "delimiter.parenthesis", "@pop"],
      [/[ \t]+/, "white"],
    ],

    narrativeLine: [
      [/^./, { token: "@rematch", next: "@pop" }],
      { include: "@comments" },
      [/\\#/, "string.escape"],
      [/#/, "delimiter.tag", "@tag"],
      { include: "@diverts" },
      [/<>/, "keyword.glue"],
      [/\{/, "delimiter.curly", "@curlyExpression"],
      [/$/, "", "@pop"],
    ],

    weaveLine: [
      [/^./, { token: "@rematch", next: "@pop" }],
      { include: "@comments" },
      [/(\()(\s*)(@identifier)(\s*)(\))/, ["delimiter.parenthesis", "white", "entity.name.label", "white", "delimiter.parenthesis"]],
      [/\[/, "delimiter.choice-bracket", "@suppression"],
      [/\\#/, "string.escape"],
      [/#/, "delimiter.tag", "@tag"],
      { include: "@diverts" },
      [/<>/, "keyword.glue"],
      [/(\{)(\s*)(stopping|cycle|once|shuffle(?:\s+(?:once|stopping))?)(\s*)(:)/, ["delimiter.curly", "white", "keyword.multiline", "white", { token: "delimiter.colon", next: "@curlyContent" }]],
      [/\{(?=[^}\r\n]*\|)/, "delimiter.curly", "@sequence"],
      [/\{(?=\s*$)/, "delimiter.curly", "@curlyContent"],
      [/\{/, "delimiter.curly", "@curlyExpression"],
      [/\bTODO\b/, "keyword.todo"],
      [/$/, "", "@pop"],
    ],

    suppression: [
      [/\\[\[\]]/, "string.escape"],
      [/\{/, "delimiter.curly", "@curlyExpression"],
      [/\]/, "delimiter.choice-bracket", "@pop"],
      [/[^\]\\{]+/, "string.content"],
      [/./, "string.content"],
    ],

    sequence: [
      { include: "@comments" },
      [/\}/, "delimiter.curly", "@pop"],
      [/\|/, "keyword.alternative"],
      [/\\#/, "string.escape"],
      [/#/, "delimiter.tag", "@tag"],
      { include: "@diverts" },
      [/<>/, "keyword.glue"],
      [/(\{)(\s*)([&~!$])(?=[^}\r\n]*\|)/, ["delimiter.curly", "white", { token: "keyword.alternative.type", next: "@sequence" }]],
      [/\{(?=[^}\r\n]*\|)/, "delimiter.curly", "@sequence"],
      [/\{/, "delimiter.curly", "@curlyExpression"],
    ],

    curlyExpression: [
      { include: "@comments" },
      [/\}/, "delimiter.curly", "@pop"],
      [/:/, { token: "delimiter.colon", switchTo: "@curlyContent" }],
      [/\|/, { token: "keyword.alternative", switchTo: "@curlyContent" }],
      [/\{/, "delimiter.curly", "@push"],
      { include: "@expression" },
    ],

    curlyContent: [
      { include: "@comments" },
      [/\}/, "delimiter.curly", "@pop"],
      [/\|/, "keyword.alternative"],
      [/^(\s*)(-)(\s*)(else\b|[^:{}|]+)(:)/, ["white", "delimiter.gather", "white", "keyword.condition", "delimiter.colon"]],
      [/^(\s*)((?:\*\s*)+)/, ["white", { token: "delimiter.choice", next: "@weaveLine" }]],
      [/^(\s*)((?:\+\s*)+)/, ["white", { token: "delimiter.choice.sticky", next: "@weaveLine" }]],
      [/^(\s*)(-)(\s+)/, ["white", "delimiter.gather", "white"]],
      [/\\#/, "string.escape"],
      [/#/, "delimiter.tag", "@tag"],
      { include: "@diverts" },
      [/<>/, "keyword.glue"],
      [/(\{)(\s*)(stopping|cycle|once|shuffle(?:\s+(?:once|stopping))?)(\s*)(:)/, ["delimiter.curly", "white", "keyword.multiline", "white", { token: "delimiter.colon", next: "@curlyContent" }]],
      [/(\{)(\s*)([&~!$])(?=[^}\r\n]*\|)/, ["delimiter.curly", "white", { token: "keyword.alternative.type", next: "@sequence" }]],
      [/\{(?=[^}\r\n]*\|)/, "delimiter.curly", "@sequence"],
      [/\{/, "delimiter.curly", "@curlyExpression"],
    ],

    expressionLine: [
      [/^./, { token: "@rematch", next: "@pop" }],
      { include: "@comments" },
      { include: "@expression" },
      [/$/, "", "@pop"],
    ],

    expression: [
      [/"/, "string.quote", "@string"],
      { include: "@diverts" },
      [/@symbols/, {
        cases: {
          "@operators": "operator",
          "@default": "operator",
        },
      }],
      [/\b\d*\.\d+([eE][\-+]?\d+)?\b/, "number.float"],
      [/\b\d+\b/, "number"],
      [/@identifier(?=\s*\()/, {
        cases: {
          "@builtInFunctions": "support.function.math",
          "@default": "entity.name.function",
        },
      }],
      [/@identifier/, {
        cases: {
          "true|false": "constant.language.boolean",
          "return": "keyword.return",
          "temp": "keyword.temp",
          "else": "keyword.else",
          "and|or|not|mod|has|hasnt": "operator.word",
          "@builtInFunctions": "support.function.math",
          "@keywords": "keyword",
          "@default": "variable.name",
        },
      }],
      [/[(),:]/, "delimiter"],
      [/[ \t]+/, "white"],
    ],

    diverts: [
      [/(->->|->|<-)(\s*)(END|DONE)\b/, ["keyword.divert", "white", "keyword.return"]],
      [/(->->|->|<-)(\s*)(@identifier)(\s*\.\s*)(@identifier)(\s*\.\s*)(@identifier)(\s*)(\()/, ["keyword.divert", "white", "variable.other.knot", "delimiter.accessor", "variable.other.stitch", "delimiter.accessor", "variable.other.label", "white", { token: "delimiter.parenthesis", next: "@callArguments" }]],
      [/(->->|->|<-)(\s*)(@identifier)(\s*\.\s*)(@identifier)(\s*)(\()/, ["keyword.divert", "white", "variable.other.knot", "delimiter.accessor", "variable.other.stitch", "white", { token: "delimiter.parenthesis", next: "@callArguments" }]],
      [/(->->|->|<-)(\s*)(@identifier)(\s*)(\()/, ["keyword.divert", "white", "variable.other.knot", "white", { token: "delimiter.parenthesis", next: "@callArguments" }]],
      [/(->->|->|<-)(\s*)(@identifier)(\s*\.\s*)(@identifier)(\s*\.\s*)(@identifier)/, ["keyword.divert", "white", "variable.other.knot", "delimiter.accessor", "variable.other.stitch", "delimiter.accessor", "variable.other.label"]],
      [/(->->|->|<-)(\s*)(@identifier)(\s*\.\s*)(@identifier)/, ["keyword.divert", "white", "variable.other.knot", "delimiter.accessor", "variable.other.stitch"]],
      [/(->->|->|<-)(\s*)(@identifier)/, ["keyword.divert", "white", "variable.other.knot"]],
      [/->->|->|<-/, "keyword.divert"],
    ],

    callArguments: [
      { include: "@comments" },
      [/\(/, "delimiter.parenthesis", "@push"],
      [/\)/, "delimiter.parenthesis", "@pop"],
      { include: "@expression" },
    ],

    string: [
      [/@escapes/, "string.escape"],
      [/\\./, "string.escape.invalid"],
      [/\{/, "delimiter.curly", "@interpolation"],
      [/[^\\{"}]+/, "string"],
      [/"/, "string.quote", "@pop"],
      [/./, "string"],
    ],

    interpolation: [
      { include: "@comments" },
      [/\}/, "delimiter.curly", "@pop"],
      [/\{/, "delimiter.curly", "@push"],
      { include: "@expression" },
      [/[ \t\r\n]+/, "white"],
    ],
  },
};

// Theme configuration for better syntax highlighting
export const inkTheme: import("monaco-editor").editor.IStandaloneThemeData = {
  base: 'vs-dark', // or 'vs' for light theme
  inherit: true,
  rules: [
    { token: 'delimiter.knot', foreground: '#bb9af7', fontStyle: 'bold' },
    { token: 'entity.name.knot', foreground: '#7dcfff', fontStyle: 'bold' },
    { token: 'entity.name.stitch', foreground: '#7dcfff', fontStyle: 'bold' },
    { token: 'entity.name.function', foreground: '#7aa2f7' },
    { token: 'entity.name.divert', foreground: '#7dcfff' },
    { token: 'entity.name.thread', foreground: '#7dcfff' },
    { token: 'entity.name.label', foreground: '#e0af68' },
    { token: 'entity.name.tag', foreground: '#7dcfff' },
    { token: 'variable.other.knot', foreground: '#7dcfff' },
    { token: 'variable.other.stitch', foreground: '#73daca' },
    { token: 'variable.other.label', foreground: '#e0af68' },
    { token: 'keyword.declaration', foreground: '#bb9af7', fontStyle: 'bold' },
    { token: 'keyword.function', foreground: '#bb9af7', fontStyle: 'italic' },
    { token: 'keyword.include', foreground: '#bb9af7' },
    { token: 'keyword.divert', foreground: '#ff9e64' },
    { token: 'keyword.thread', foreground: '#ff9e64' },
    { token: 'keyword.return', foreground: '#f7768e' },
    { token: 'keyword.temp', foreground: '#bb9af7' },
    { token: 'keyword.else', foreground: '#bb9af7' },
    { token: 'keyword.multiline', foreground: '#e0af68' },
    { token: 'keyword.condition', foreground: '#e0af68' },
    { token: 'keyword.parameter', foreground: '#bb9af7' },
    { token: 'keyword.alternative.type', foreground: '#e0af68', fontStyle: 'bold' },
    { token: 'keyword.tilde', foreground: '#bb9af7' },
    { token: 'keyword.glue', foreground: '#89ddff' },
    { token: 'keyword.alternative', foreground: '#e0af68' },
    { token: 'keyword.todo', foreground: '#f7768e', fontStyle: 'bold' },
    { token: 'keyword', foreground: '#bb9af7' },
    { token: 'variable.global', foreground: '#7aa2f7' },
    { token: 'variable.constant', foreground: '#ff9e64' },
    { token: 'variable.list', foreground: '#73daca' },
    { token: 'variable.name', foreground: '#c0caf5' },
    { token: 'support.function.math', foreground: '#2ac3de' },
    { token: 'constant.language.boolean', foreground: '#ff9e64' },
    { token: 'constant.language.null', foreground: '#ff9e64' },
    { token: 'delimiter.choice', foreground: '#e0af68', fontStyle: 'bold' },
    { token: 'delimiter.gather', foreground: '#7aa2f7', fontStyle: 'bold' },
    { token: 'delimiter.choice-bracket', foreground: '#e0af68' },
    { token: 'delimiter.tag', foreground: '#7dcfff', fontStyle: 'bold' },
    { token: 'delimiter.curly', foreground: '#89ddff' },
    { token: 'delimiter.colon', foreground: '#89ddff' },
    { token: 'delimiter', foreground: '#89ddff' },
    { token: 'comment', foreground: '#565f89' },
    { token: 'number', foreground: '#ff9e64' },
    { token: 'string.filename', foreground: '#9ece6a' },
    { token: 'string.escape', foreground: '#2ac3de' },
    { token: 'string.escape.invalid', foreground: '#f7768e' },
    { token: 'string', foreground: '#9ece6a' },
    { token: 'string.content', foreground: '#9ece6a' },
    { token: 'operator.word', foreground: '#89ddff' },
    { token: 'operator', foreground: '#89ddff' },
    { token: 'invalid', foreground: '#f7768e' },
  ],
  colors: {
    'editor.background': '#1a1b26',
    'editor.foreground': '#c0caf5',
    'editorLineNumber.foreground': '#737aa2',
    'editor.lineHighlightBackground': '#292e4266', // Slightly brighter line highlight with opacity
    'editorCursor.foreground': '#c0caf5',
    'editor.selectionBackground': '#bb9af744', // Lighter purple for active selections
    'editor.selectionHighlightBackground': '#bb9af744', // Purple highlight for matching words
    'editor.wordHighlightBackground': '#bb9af744', // Purple for variable highlighting
    'editor.wordHighlightStrongBackground': '#bb9af766',
    'editor.findMatchBackground': '#bb9af788',
    'editor.findMatchHighlightBackground': '#bb9af744',
    'editorIndentGuide.background': '#1f2335',
    'editorIndentGuide.activeBackground': '#3b4261',
    'editorWidget.background': '#1f2335',
    'editorWidget.foreground': '#c0caf5',
    'editorWidget.border': '#3b4261',
    'editorWidget.resizeBorder': '#7aa2f7',
    'widget.shadow': '#0f101766',
    'input.background': '#1a1b26',
    'input.foreground': '#c0caf5',
    'input.border': '#3b4261',
    'input.placeholderForeground': '#737aa2',
    'focusBorder': '#7aa2f7',
    'toolbar.hoverBackground': '#292e42',
    'toolbar.activeBackground': '#3b4261',
    'disabledForeground': '#737aa2',
    'errorForeground': '#f7768e',
  }
};

export const inkThemeHighContrast: import("monaco-editor").editor.IStandaloneThemeData = {
  base: "hc-black",
  inherit: true,
  rules: [
    { token: "delimiter.knot", foreground: "#FFFF00", fontStyle: "bold" },
    { token: "entity.name.knot", foreground: "#00FFFF", fontStyle: "bold" },
    { token: "entity.name.stitch", foreground: "#00FFFF", fontStyle: "bold" },
    { token: "entity.name.function", foreground: "#00FFFF" },
    { token: "entity.name.divert", foreground: "#00FFFF" },
    { token: "entity.name.thread", foreground: "#00FFFF" },
    { token: "entity.name.label", foreground: "#FFFF00" },
    { token: "entity.name.tag", foreground: "#FFFFFF" },
    { token: "variable.other.knot", foreground: "#00FFFF" },
    { token: "variable.other.stitch", foreground: "#72FF72" },
    { token: "variable.other.label", foreground: "#FFFF00" },
    { token: "keyword", foreground: "#FFFF00", fontStyle: "bold" },
    { token: "keyword.declaration", foreground: "#FFFF00", fontStyle: "bold" },
    { token: "keyword.function", foreground: "#FFFF00" },
    { token: "keyword.include", foreground: "#FFFF00" },
    { token: "keyword.divert", foreground: "#00FFFF" },
    { token: "keyword.thread", foreground: "#00FFFF" },
    { token: "keyword.return", foreground: "#FF6B6B" },
    { token: "keyword.condition", foreground: "#FFFF00" },
    { token: "keyword.parameter", foreground: "#FFFF00" },
    { token: "keyword.alternative.type", foreground: "#FFFF00", fontStyle: "bold" },
    { token: "variable.global", foreground: "#FFFFFF" },
    { token: "variable.constant", foreground: "#00FFFF" },
    { token: "variable.list", foreground: "#72FF72" },
    { token: "variable.name", foreground: "#FFFFFF" },
    { token: "delimiter.choice", foreground: "#FFFF00", fontStyle: "bold" },
    { token: "delimiter.gather", foreground: "#00FFFF", fontStyle: "bold" },
    { token: "delimiter.tag", foreground: "#FFFFFF", fontStyle: "bold" },
    { token: "comment", foreground: "#D6D6D6" },
    { token: "number", foreground: "#00FFFF" },
    { token: "string.filename", foreground: "#72FF72" },
    { token: "string", foreground: "#72FF72" },
    { token: "string.content", foreground: "#72FF72" },
    { token: "operator", foreground: "#FFFF00" },
    { token: "operator.word", foreground: "#FFFF00" },
    { token: "invalid", foreground: "#FF6B6B" },
  ],
  colors: {
    "editor.background": "#000000",
    "editor.foreground": "#FFFFFF",
    "editorLineNumber.foreground": "#D6D6D6",
    "editor.lineHighlightBackground": "#202020",
    "editorCursor.foreground": "#FFFF00",
    "editor.selectionBackground": "#005A9C",
    "editor.findMatchBackground": "#7A5200",
    "editorWidget.background": "#000000",
    "editorWidget.foreground": "#FFFFFF",
    "editorWidget.border": "#FFFFFF",
    "input.background": "#000000",
    "input.foreground": "#FFFFFF",
    "input.border": "#FFFFFF",
    "focusBorder": "#FFFF00",
  },
};

export const inkThemeLight: import("monaco-editor").editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'delimiter.knot', foreground: '#a755ed', fontStyle: 'bold' },
    { token: 'entity.name.knot', foreground: '#0ea5e9', fontStyle: 'bold' },
    { token: 'entity.name.stitch', foreground: '#0ea5e9', fontStyle: 'bold' },
    { token: 'entity.name.function', foreground: '#2563eb' },
    { token: 'entity.name.divert', foreground: '#0ea5e9' },
    { token: 'entity.name.thread', foreground: '#0ea5e9' },
    { token: 'entity.name.label', foreground: '#f58e1d' },
    { token: 'entity.name.tag', foreground: '#e82e6c' },
    { token: 'variable.other.knot', foreground: '#0ea5e9' },
    { token: 'variable.other.stitch', foreground: '#178f7d' },
    { token: 'variable.other.label', foreground: '#f58e1d' },
    { token: 'keyword.declaration', foreground: '#a755ed', fontStyle: 'bold' },
    { token: 'keyword.function', foreground: '#a755ed', fontStyle: 'italic' },
    { token: 'keyword.include', foreground: '#a755ed' },
    { token: 'keyword.divert', foreground: '#eb6b2f' },
    { token: 'keyword.thread', foreground: '#eb6b2f' },
    { token: 'keyword.return', foreground: '#e82e6c' },
    { token: 'keyword.temp', foreground: '#a755ed' },
    { token: 'keyword.else', foreground: '#a755ed' },
    { token: 'keyword.multiline', foreground: '#f58e1d' },
    { token: 'keyword.condition', foreground: '#f58e1d' },
    { token: 'keyword.parameter', foreground: '#a755ed' },
    { token: 'keyword.alternative.type', foreground: '#f58e1d', fontStyle: 'bold' },
    { token: 'keyword.tilde', foreground: '#a755ed' },
    { token: 'keyword.glue', foreground: '#0ea5e9' },
    { token: 'keyword.alternative', foreground: '#f58e1d' },
    { token: 'keyword.todo', foreground: '#e82e6c', fontStyle: 'bold' },
    { token: 'keyword', foreground: '#a755ed' },
    { token: 'variable.global', foreground: '#5c68fc' },
    { token: 'variable.constant', foreground: '#eb6b2f' },
    { token: 'variable.list', foreground: '#178f7d' },
    { token: 'variable.name', foreground: '#5c68fc' },
    { token: 'support.function.math', foreground: '#0891b2' },
    { token: 'constant.language.boolean', foreground: '#eb6b2f' },
    { token: 'constant.language.null', foreground: '#eb6b2f' },
    { token: 'delimiter.choice', foreground: '#f58e1d', fontStyle: 'bold' },
    { token: 'delimiter.gather', foreground: '#0ea5e9', fontStyle: 'bold' },
    { token: 'delimiter.choice-bracket', foreground: '#f58e1d' },
    { token: 'delimiter.tag', foreground: '#e82e6c', fontStyle: 'bold' },
    { token: 'delimiter.curly', foreground: '#0ea5e9' },
    { token: 'delimiter.colon', foreground: '#0ea5e9' },
    { token: 'delimiter', foreground: '#0ea5e9' },
    { token: 'comment', foreground: '#9499b8' },
    { token: 'number', foreground: '#eb6b2f' },
    { token: 'string.filename', foreground: '#178f7d' },
    { token: 'string.escape', foreground: '#0891b2' },
    { token: 'string.escape.invalid', foreground: '#e82e6c' },
    { token: 'string', foreground: '#178f7d' },
    { token: 'string.content', foreground: '#178f7d' },
    { token: 'operator.word', foreground: '#0ea5e9' },
    { token: 'operator', foreground: '#0ea5e9' },
    { token: 'invalid', foreground: '#e82e6c' },
  ],
  colors: {
    'editor.background': '#f1f3f7',
    'editor.foreground': '#42486f',
    'editorLineNumber.foreground': '#a9adcc',
    'editor.lineHighlightBackground': '#e5e8f5', 
    'editorCursor.foreground': '#5c68fc',
    'editor.selectionBackground': '#5c68fc33', 
    'editor.selectionHighlightBackground': '#a755ed22', 
    'editor.wordHighlightBackground': '#a755ed22', 
    'editor.wordHighlightStrongBackground': '#a755ed44',
    'editor.findMatchBackground': '#5c68fc55',
    'editor.findMatchHighlightBackground': '#5c68fc33',
    'editorIndentGuide.background': '#dcdff0',
    'editorIndentGuide.activeBackground': '#a9adcc',
    'editorWidget.background': '#e9ebf2',
    'editorWidget.foreground': '#42486f',
    'editorWidget.border': '#d2d5de',
    'editorWidget.resizeBorder': '#5c68fc',
    'widget.shadow': '#42486f26',
    'input.background': '#f1f3f7',
    'input.foreground': '#1f2447',
    'input.border': '#d2d5de',
    'input.placeholderForeground': '#7d829d',
    'focusBorder': '#5c68fc',
    'toolbar.hoverBackground': '#dcdff0',
    'toolbar.activeBackground': '#d2d5de',
    'disabledForeground': '#a9adcc',
    'errorForeground': '#e82e6c',
  }
};

// Configuration for Monaco Editor
export const inkLanguageConfig: languages.LanguageConfiguration = {
  comments: {
    lineComment: '//',
    blockComment: ['/*', '*/'],
  },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')']
  ],
  autoClosingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' }
  ],
  surroundingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' }
  ]
};
